config/routes.rb
Rails.application.routes.draw do

  root :to => 'main#home'

  get 'main' => 'main#show'

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

	resources :protocol_admin do
    resources :sheets
  end

  resources :stat_non_pat_adults
  resources :patients

  get 'admin' => 'admin/admin#index'

	namespace :admin do
		resources :users
		resources :interpretations
		resources :sheets do
      resources :areas do
        resources :zones, :allowed_interpretations, :interpretations
      end
    end
	end

end

app/models/allowed_interpretation.rb
class AllowedInterpretation < ActiveRecord::Base
	belongs_to :area
end

app/controllers/admin/allowed_interpretations_controller.rb
class Admin::AllowedInterpretationsController < ApplicationController
  before_action :set_allowed_interpretation, only: [:show, :edit, :update, :destroy]

  # GET /allowed_interpretations
  # GET /allowed_interpretations.json
  def index
  	@sheet = Sheet.find_by_id(params[:sheet_id])
    @area = Area.find_by_id(params[:area_id])
    @allowed_interpretations = @area.allowedInterpretations
  end

  # GET /allowed_interpretations/1
  # GET /allowed_interpretations/1.json
  def show
  	@sheet = Sheet.find_by_id(params[:sheet_id])
    @area = Area.find_by_id(params[:area_id])
  end

  # GET /allowed_interpretations/new
  def new
    @sheet = Sheet.find_by_id(params[:sheet_id])
    @area = Area.find_by_id(params[:area_id])
    @allowed_interpretation = AllowedInterpretation.new
  end

  # GET /allowed_interpretations/1/edit
  def edit
    @sheet = Sheet.find_by_id(params[:sheet_id])
    @area = Area.find_by_id(params[:area_id])
  end

  # POST /allowed_interpretations
  # POST /allowed_interpretations.json
  def create
    @allowed_interpretation = AllowedInterpretation.new(allowed_interpretation_params)
    @area = Area.find_by_id(params[:area_id])
    @area.allowedInterpretations.push(@allowed_interpretation)

    respond_to do |format|
      if @area.save
        format.html { redirect_to new_admin_sheet_area_allowed_interpretation_path(params[:sheet_id], params[:area_id]), notice: 'Allowed interpretation was successfully created.' }
        format.json { render :show, status: :created, location: @allowed_interpretation }
      else
        format.html { render :new }
        format.json { render json: @allowed_interpretation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allowed_interpretations/1
  # PATCH/PUT /allowed_interpretations/1.json
  def update
    respond_to do |format|
      if @allowed_interpretation.update(allowed_interpretation_params)
        format.html { redirect_to admin_sheet_area_allowed_interpretations_path(params[:sheet_id], params[:area_id]), notice: 'Allowed interpretation was successfully updated.' }
        format.json { render :show, status: :ok, location: @allowed_interpretation }
      else
        format.html { render :edit }
        format.json { render json: @allowed_interpretation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allowed_interpretations/1
  # DELETE /allowed_interpretations/1.json
  def destroy
    @allowed_interpretation.destroy
    respond_to do |format|
      format.html { redirect_to admin_sheet_area_allowed_interpretations_path, notice: 'Allowed interpretation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allowed_interpretation
      @allowed_interpretation = AllowedInterpretation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allowed_interpretation_params
      params.require(:allowed_interpretation).permit(:name, :description, :direction, :formal_quality)
    end
end

app/controllers/allowed_interpretations_controller.rb
class AllowedInterpretationsController < ApplicationController
end

app/helpers/allowed_interpretations_helper.rb
module AllowedInterpretationsHelper
end

app/views/admin/allowed_interpretations/_form.html.erb
<%= form_for [:admin, @sheet, @area, @allowed_interpretation] do |f| %>
  <% if @allowed_interpretation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@allowed_interpretation.errors.count, "error") %> prohibited this allowed_interpretation from being saved:</h2>
      <ul>
      <% @allowed_interpretation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :direction %><br>
    <%= f.text_field :direction %>
  </div>
  <div class="field">
    <%= f.label :formal_quality %><br>
    <%= f.text_field :formal_quality %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/allowed_interpretations/edit.html.erb
<h1>Editing allowed_interpretation</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_sheet_area_allowed_interpretation_path(@allowed_interpretation) %> |
<%= link_to 'Back', admin_sheet_area_allowed_interpretations_path(@sheet, @area) %>

app/views/admin/allowed_interpretations/index.html.erb
<h1>Listing allowed_interpretations</h1>

<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Direction</th>
      <th>Formal quality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if !@allowed_interpretations.nil?  %>
      <% @allowed_interpretations.each do |allowed_interpretation| %>
        <tr>
          <td><%= allowed_interpretation.name %></td>
          <td><%= allowed_interpretation.description %></td>
          <td><%= allowed_interpretation.direction %></td>
          <td><%= allowed_interpretation.formal_quality %></td>
          <td><%= link_to 'Show', admin_sheet_area_allowed_interpretation_url(@sheet, @area, allowed_interpretation) %></td>
          <td><%= link_to 'Edit', edit_admin_sheet_area_allowed_interpretation_url(@sheet, @area, allowed_interpretation) %></td>
          <td><%= link_to 'Destroy', admin_sheet_area_allowed_interpretation_url(@sheet, @area, allowed_interpretation), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Allowed interpretation', new_admin_sheet_area_allowed_interpretation_path %> |
<%= link_to 'Back', admin_sheet_areas_path(@sheet) %>

app/views/admin/allowed_interpretations/new.html.erb
<h1>New allowed_interpretation</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_sheet_area_allowed_interpretations_path %>

app/views/admin/allowed_interpretations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @allowed_interpretation.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @allowed_interpretation.description %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @allowed_interpretation.direction %>
</p>

<p>
  <strong>Formal quality:</strong>
  <%= @allowed_interpretation.formal_quality %>
</p>

<%= link_to 'Edit', edit_admin_sheet_area_allowed_interpretation_path(@allowed_interpretation) %> |
<%= link_to 'Back', admin_sheet_area_allowed_interpretations_path %>