config/routes.rb
Rails.application.routes.draw do

  root :to => 'main#home'

  get 'main' => 'main#show'

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

	resources :protocol_admin do
    resources :sheets
  end

  resources :stat_non_pat_adults
  resources :patients

  get 'admin' => 'admin/admin#index'

	namespace :admin do
		resources :users
		resources :interpretations
		resources :sheets do
      resources :areas do
        resources :zones, :allowed_interpretations, :interpretations
      end
    end
	end

end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
	has_many :areas, :dependent => :destroy
end

app/controllers/admin/sheets_controller.rb
#controlador administrador
class Admin::SheetsController < ApplicationController
	before_action :set_sheet, only: [:show, :edit, :update, :destroy]

	# GET /sheets
	# GET /sheets.json
	def index
	  @sheets = Sheet.all
	end

	# GET /sheets/1
	# GET /sheets/1.json
	def show
  	  @sheets = Sheet.all
	end

	# GET /sheets/new
	def new
	  @sheet = Sheet.new
	end

	# GET /sheets/1/edit
	def edit
	end

	# POST /sheets
	# POST /sheets.json
	def create
	  @sheet = Sheet.new(sheet_params)

	  respond_to do |format|
	    if @sheet.save
	      format.html { redirect_to @sheet, notice: 'Sheet was successfully created.' }
	      format.json { render :show, status: :created, location: @sheet }
	    else
	      format.html { render :new }
	      format.json { render json: @sheet.errors, status: :unprocessable_entity }
	    end
	  end
	end

	# PATCH/PUT /sheets/1
	# PATCH/PUT /sheets/1.json
	def update
	  respond_to do |format|
	    if @sheet.update(sheet_params)
	      format.html { redirect_to @sheet, notice: 'Sheet was successfully updated.' }
	      format.json { render :show, status: :ok, location: @sheet }
	    else
	      format.html { render :edit }
	      format.json { render json: @sheet.errors, status: :unprocessable_entity }
	    end
	  end
	end

	# DELETE /sheets/1
	# DELETE /sheets/1.json
	def destroy
	  @sheet.destroy
	  respond_to do |format|
	    format.html { redirect_to admin_sheets_path, notice: 'Sheet was successfully destroyed.' }
	    format.json { head :no_content }
	  end
	end

	private
	  # Use callbacks to share common setup or constraints between actions.
	  def set_sheet
	    @sheet = Sheet.find(params[:id])
	  end

	  # Never trust parameters from the scary internet, only allow the white list through.
	  def sheet_params
	    params.require(:sheet).permit(:name, :background)
	  end
end

app/controllers/sheets_controller.rb
#controlador usuarios
class SheetsController < ApplicationController
  before_action :set_sheet, only: [:show, :edit, :update, :destroy]

  # GET protocol_admin/1/sheets
  # GET protocol_admin/1/sheets.json
  def index
    @sheets = Sheet.all
  end

  # GET protocol_admin/1/sheets/1
  # GET protocol_admin/1/sheets/1.json
  def show
    @protocol=RorschachTest.find_by(id: protocol_admin_params[:protocol_admin_id])
    @patient=@protocol.patient
  end

  # GET protocol_admin/1/sheets/new
  def new
    @sheet = Sheet.new
  end

  # GET protocol_admin/1/sheets/1/edit
  def edit
    #id del protocolo
    @protocol = RorschachTest.find_by(id: protocol_admin_params[:protocol_admin_id])
    #array con valores para select de direction
    @direction = [['^', 1], ['>', 2], ['<', 3], ['v', 4]]
    #array con valores para select de fq
    @fq= [['+', 1], ['o', 2], ['u', 3], ['-', 4]]
    #array con valores para select de dq
    @dq= [['+', 1], ['o', 2], ['v/+', 3], ['v', 4]]
    #array de zones disponibles en la sheet
    #recorrer todas las areas de la sheet, y filtrar las zones repetidas
    zones=Array.new
    @sheet.areas.each do |area|
      area.zones.each do |zone|
        zones.push(zone)
      end
    end
    @zonesUnique=zones.uniq { |s| s.id }
  end

  # POST /sheets
  # POST /sheets.json
  def create
    @sheet = Sheet.new(sheet_params)

    respond_to do |format|
      if @sheet.save
        format.html { redirect_to @sheet, notice: 'Sheet was successfully created.' }
        format.json { render :show, status: :created, location: @sheet }
      else
        format.html { render :new }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sheets/1
  # PATCH/PUT /sheets/1.json
  def update
    respond_to do |format|
      if @sheet.update(sheet_params)
        format.html { redirect_to @sheet, notice: 'Sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @sheet }
      else
        format.html { render :edit }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sheets/1
  # DELETE /sheets/1.json
  def destroy
    @sheet.destroy
    respond_to do |format|
      format.html { redirect_to sheets_url, notice: 'Sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sheet
      # debo buscar la lamina que corresponde al protocolo a editar.
      @sheet = Sheet.find_by(id: sheet_params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sheet_params
      params.permit(:id)
    end

    def protocol_admin_params
      params.permit(:protocol_admin_id)
    end
end

app/helpers/admin/sheets_helper.rb
module Admin::SheetsHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/sheets/_editSheet_helper.html.erb
<div id="container" class="container">
	<div class="row">
		<div class="col-12">
			<%= form_for admin_interpretations_path do |f| %>
				<p>Controles</p>
				<% if @interpretation && @interpretation.errors.any? %>
					<div class="row">
						<div class="col-12">
							<div id="error_explanation">
								<h2><%= pluralize(@interpretation.errors.count, "error") %> prohibited this interpretation from being saved:</h2>
								<ul>
									<% @interpretation.errors.full_messages.each do |message| %>
										<li><%= message %></li>
									<% end %>
								</ul>
							</div>
						</div>
					</div>
				<% end %>
			<div id="main-container" class="container formControls">
				<div id="interpretationControls" class="row">
					<!-- Interpretation attr for new records -->
					<!-- div "localization" -->
					<div class="col-xs-6 col-sm-4 col-md-4">
						<!-- Label "Localizacion" -->
						<p>Localization</p>
						<!-- Text area "areaCode" -->
						<!-- aqui se va a ir autocompletando la codificacion global de la respuesta: "Mªd, TFu, FC.FD-, FMª.FC'+" -->
						<div class="field formControls">
							<%= f.label :globalResp %>
							<%= f.text_area :globalResp, :readonly => true %>
						</div>
						<!-- checkbox "globalResp" -->
						<div class="field formControls">
							<%= f.label :"Respuesta Global (W)" %>
							<!-- al marcar la casilla W se debe deshabilitar el resto de los controles del form, ver cuales pueden permanecer editables y cuales no.-->
							<%= f.check_box :globalRespW_CheckBox %>
							<%= f.label :"Respuesta Global (WS)" %>
							<%= f.check_box :globalRespWS_CheckBox %>
						</div>
						<!-- checkbox "undefinedRes_Dd99" -->
						<div id="div_ndefinedRes_Dd99" class="field formControls">
							<%= f.label :"Localización no definida (Dd99)" %>
							<%= f.check_box :undefinedRes_Dd99 %>
							<%= f.label :"Localización no definida (DdS99)" %>
							<%= f.check_box :undefinedRes_DdS99 %>
						</div>
						<!-- comboBox "direction" -->
						<div id="div_direction" class="field formControls">
							<%= f.label :direction %>
							<%= f.select :direction, @direction %>
						</div>
					</div>

					<!-- div "respContents" -->
					<div class="col-xs-6 col-sm-4 col-md-4">
						<p>Contenido de la Respuesta</p>
							<!-- div "popularContents" -->
							<div id="popularContents">
								<div class="field formControls">
									<%= f.label :"Contenidos populares" %>
									<%= f.select :popularContentsCombo, ["",] %>
								</div>
								<!-- div "Determinants" -->
								<div class="field formControls">
									<%= f.label :Determinantes %>
									<%= f.select :detCombo, ["",] %>
								</div>
								<!-- option 24 elementos -->
							</div>

							<!-- div "FQ, Calidad Formal" -->
							<div id="FQ">
								<div class="field formControls">
									<%= f.label :"Calidad Formal (FQ)" %>
									<%= f.select :fq,  @fq %>
								</div>
							</div>
					</div>

					<!-- div "DQ, Calidad Evolutiva" -->
					<div class="col-xs-6 col-sm-4 col-md-4">
							<div class="field formControls">
								<%= f.label :"Calidad Evolutiva (DQ)" %>
								<%= f.select :dq,  @dq %>
							</div>
					</div>
				</div>

				<!-- div "OrgActivity, Actividad Organizativa" -->
				<div class="row">
					<div class="col-xs-6 col-sm-4 col-md-4">
						<div class="field formControls">
							<%= f.label :"Actividad Organizativa" %>
						</div>
					</div>

					<!-- div "SpecialCodes, Codigos Especiales" -->
					<div class="col-xs-6 col-sm-4 col-md-4">
						<div class="field formControls">
							<%= f.label :"Codigos Especiales" %>
						</div>
					</div>

					<!-- Text area "obs" -->
					<div class="col-xs-6 col-sm-4 col-md-4">
						<div class="field formControls">
							<%= f.label :"Observaciones" %>
							<%= f.text_area :obs %>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="field formControls">
						<div class="actions">
							<!-- Button trigger modal: ver lamina original "viewSheet" -->
							<button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal">
							  Mostrar lámina
							</button>
							<!-- Button submit remote:on -->
							<%= f.submit("OK", {class: "btn btn-primary"}) %>
							<!-- Button Cancel -->
							<%= button_tag "Cancelar", type: 'button', onclick: "clean_interpretationForm(){return;}", class: 'btn btn-danger' %>
						</div>
					</div>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ver lámina</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/sheets/_form.html.erb
<%= form_for protocol_admin_sheet_path do |f| %>
  <% if @sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sheet.errors.count, "error") %> prohibited this sheet from being saved:</h2>

      <ul>
        <% @sheet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- Sheet attr for new records -->
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :background %><br>
    <%= f.text_field :background %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sheets/edit.html.erb
<div id="head" class="text-center" style="max-width: 100%;">
	<h1><%= "Editing sheet #{@sheet.id} on Protocol #{@protocol.id}: #{@protocol.patient.given_name} #{@protocol.patient.last_name}" %></h1>
	<br></br>
</div>
<!-- Base sheet + zone btns + form for interpretations -->
<div id="box">
  	<%= image_tag (@sheet.background), class: "static" %>
	<% @zonesUnique.each do |zone| %>
		<%= image_tag (zone.bg_image), class: "area", id: "l"+"_"+zone.id.to_s %>
	<% end %>

<button class="clearButton_sheet" onclick="reset_areas();">Reestablecer</button>
<%= button_to "Ingresar", { action: "create" }, class: "addButton_sheet", remote: true, form: { "data-type" => "json" } %>

</div>

<br></br>

<div id="main-container" class="container formControls">
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-8 formControls">.col-xs-12 .col-sm-6 .col-md-8</div>
  <div class="col-xs-8 col-sm-2 col-md-2 formControls">.col-xs-8 .col-sm-2 .col-md-2</div>
  <div class="col-xs-6 col-md-4 formControls">.col-xs-6 .col-md-4</div>
</div>
<div class="row">
  <div class="col-xs-6 col-sm-4 formControls">.col-xs-6 .col-sm-4</div>
  <div class="col-xs-6 col-sm-4 formControls">.col-xs-6 .col-sm-4</div>
  <!-- Optional: clear the XS cols if their content doesn't match in height -->
  <div class="clearfix visible-xs-block"></div>
  <div class="col-xs-6 col-sm-4 formControls">.col-xs-6 .col-sm-4</div>
</div>
</div>

<div id="container" class="container">
	<div class="row">
		<div class="col-xs-12">
			<p>Selector de Areas</p>
			<div id="areaButtons">
				<% @sheet.areas.each do |area| %>
					<% arr_zones=Array.new %>
					<% area.zones.each do |zone| %>
						<% arr_zones.push(zone.id)  %>
					<% end %>
					<button id="<%= area.id %>" arr_zones="<%= arr_zones %>" name="areaButton">
						<%= area.code %>
					</button>
				<% end %>
			</div>
		</div>
	</div>
</div>
<br></br>

<!-- Form for interpretations -->
<!-- Controls for add in interpretation line -->
	<%= render 'editSheet_helper' %> 
<br></br>

<!-- List of interpretations made -->
<!-- Show in here every interpretation added, showing a minimap in each line and a brief of options selected -->
<div class="container">
	<div class="row">
		<div class="col">
			<p>Listado de Interpretaciones</p>
			<div id="interpretationList" style="border-style: solid;">
				<%= render 'showInterpretationMinilist_helper' %> 
			<!-- Mini sheet -->
			</div>
		</div>
	</div>
</div>
<br></br>

<%= link_to 'Show', @id %> |
<%= link_to 'Back', protocol_admin_sheet_path %>

app/views/sheets/index.html.erb
<h1>Listing sheets</h1>

<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Background</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sheets.each do |sheet| %>
      <tr>
        <td><%= sheet.name %></td>
        <td><%= sheet.background %></td>
        <td><%= link_to 'Show', sheet %></td>
        <td><%= link_to 'Edit', edit_admin_sheet_path(sheet) %></td>
        <td><%= link_to 'Destroy', sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sheet', new_admin_sheet_path %>

app/views/sheets/new.html.erb
<h1>New sheet</h1>
<h1>BORRAR</h1>

<%= render 'form' %>

<%= link_to 'Back', sheets_path %>

app/views/sheets/show.html.erb
<p>Nombre del Paciente: <%= @patient.given_name+" "+@patient.last_name %></p>
<p>Fecha: <%= @protocol.created_at %></p>
<p>Test: <%= @protocol.id %></p>

<h1 style="text-align: center;"><strong>Lámina <%= @sheet.name %></strong></h1>
<div id="Fondo" style="margin-left: auto; margin-right: auto; width:770px; height:578px;z-index:1; visibility:visible; border-style: solid;background-image: url(<%= asset_path @sheet.background %>);"> </div>

<%= link_to 'Edit', edit_protocol_admin_sheet_path(@protocol, @sheet) %> |
<%= link_to 'Back', protocol_admin_path(@protocol) %>