config/routes.rb
Rails.application.routes.draw do

  root :to => 'main#home'

  get 'main' => 'main#show'

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

	resources :protocol_admin do
    resources :sheets
  end

  resources :stat_non_pat_adults
  resources :patients

  get 'admin' => 'admin/admin#index'

	namespace :admin do
		resources :users
		resources :interpretations
		resources :sheets do
      resources :areas do
        resources :zones, :allowed_interpretations, :interpretations
      end
    end
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveRecord::Base
	belongs_to :sheet
	has_and_belongs_to_many :zones
	has_many :allowedInterpretations
	has_many :interpretations
end

app/models/decimal.rb
class Decimal < ActiveRecord::Base
end

app/models/interpretation.rb
class Interpretation < ActiveRecord::Base
	belongs_to :rorschachTest
	belongs_to :area
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :rorschachTests, :dependent => :destroy
	has_many :users, through: :rorschachTests
end

app/models/rorschach_test.rb
class RorschachTest < ActiveRecord::Base
	belongs_to :user
	belongs_to :patient
	has_many :interpretations, :dependent => :destroy, foreign_key: :rorschachTest_id
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
	has_many :areas, :dependent => :destroy
end

app/models/stat_non_pat_adult.rb
class StatNonPatAdult < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :rorschachTests
  has_many :patients, through: :rorschachTests
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, uniqueness: true
end

app/models/zone.rb
class Zone < ActiveRecord::Base
	has_and_belongs_to_many :areas
end

app/controllers/main_controller.rb
 class MainController < ApplicationController
 	#no autenticar, salvo que se este pidiendo home
	skip_before_action :require_login, only: [:home]

	def show
  end

  def home
  end
end

app/controllers/protocol_admin_controller.rb
class ProtocolAdminController < ApplicationController

  def index
    #mostrar todos los prototoclos que existan y que pertenezcan al usuario y/o misma institucion
    #si no hay un protocolo poner un link a new
    @protocols=current_user.rorschachTests
    otherPatients=Patient.where(institution: current_user.institution)

    otherPatients.each do |patient|
      if patient.rorschachTests != nil then
       @protocols << patient.rorschachTests
      end
    end
    return @protocols
  end

  def edit
    @id=protocol_params[:id]
    #mostrar laminas
  end

  def new
    #mostrar formulario, donde elegir un usuario para pasarle a "create" y generar el protocolo nuevo
  end

  def create
    @patient=Patient.find_by(last_name: patient_params[:last_name])
    #generacion de un nuevo objeto rorschachTest
    current_user.patients.push(@patient)

  	respond_to do |format|
  	  if current_user.save
  	    format.html { redirect_to protocol_admin_path(current_user.rorschachTests.all.last), notice: 'Protocol was successfully created.' }
  	    format.json { render :show, status: :created, location: protocol_admin_path }
  	  else
  	    format.html { render :index }
  	    format.json { render json: current_user.rorschachTests.all.last, status: :unprocessable_entity }
  	  end
  	end
  end

  def show
  	# mostrar para consultas los resultados de un determinado protocolo
    @protocol=RorschachTest.find_by(id: protocol_params[:id])
    @patient=@protocol.patient
    @sheets = Sheet.all
  end

  def destroy
    #eliminar un protocolo
    @protocol=RorschachTest.find_by(id: protocol_params[:id])
    @protocol.destroy
    respond_to do |format|
      format.html { redirect_to protocol_admin_index_path, notice: 'Protocol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def protocol_params
      params.permit(:id)
    end

  	def patient_params
  		params.require(:patient).permit(:id, :given_name, :last_name, :phone, :age, :sex, :isPatient, :user, :institution)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :given_name, :last_name, :licence_number, :institution, :phone)
    end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to zones_url, notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:coord_x, :coord_y, :width, :height, :z_index, :bg_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/protocol_admin_helper.rb
module ProtocolAdminHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/protocol_admin/_form.html.erb
<%= form_tag({controller: "protocol_admin", action: "create"}, method: "post") do %>
  <%= fields_for current_user do |user| %>
      <div class="field">
        <%= user.label :full_name, "Profesional a cargo" %><br>
        <%= user.text_field :full_name, :value => current_user.given_name+" "+current_user.last_name %>
      </div>
      <div class="field">
        <%= user.label :institution, "Institución" %><br>
        <%= user.text_field :institution, :value => current_user.institution %>
      </div>
  <% end %>

  <div class="field">
    <%= label_tag :patient, "Paciente por apellido:" %>
    <%= search_field(:patient, :last_name) %>
  </div>
  </br>
  <%= submit_tag("Nuevo Protocolo") %>
<% end %>

app/views/protocol_admin/create.html.erb
<h1>ProtocolAdmin#create</h1>
<p>Find me in app/views/protocol_admin/create.html.erb</p>

app/views/protocol_admin/destroy.html.erb
<h1>ProtocolAdmin#destroy</h1>
<p>Find me in app/views/protocol_admin/destroy.html.erb</p>

app/views/protocol_admin/index.html.erb
<h1>Administrar Protocolos</h1>
<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th>Fecha de Alta</th>
      <th>Paciente</th>
      <th>Profesional</th>
      <th colspan="3">accion</th>
    </tr>
  </thead>
<% @protocols.each do |protocol| %>
  <tr>
    <td><%= protocol.created_at.localtime.strftime("%d-%m-%Y %H:%M:%S") %></td>
    <td><%= protocol.patient.given_name+" "+protocol.patient.last_name %></td>
    <td><%= protocol.user.given_name+" "+protocol.user.last_name %></td>
    <td><%= link_to 'Mostrar', protocol_admin_path(protocol) %></td>
    <td><%= link_to 'Editar', edit_protocol_admin_path(protocol) %></td>
    <td><%= link_to 'Eliminar', protocol_admin_path(protocol), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br/ >
<%= link_to 'Back', admin_path %>

app/views/protocol_admin/new.html.erb
<h1>Nuevo Protocolo</h1>
</br>
<h2>Seleccione un paciente y un profesional para generar un protocolo nuevo</h2>
</br>
<%= render 'form' %>

<%= link_to 'Back', main_path %>

app/views/protocol_admin/show.html.erb
<h1>Administrar Protocolos</h1>

<p>Nombre del Paciente: <%= @patient.given_name+" "+@patient.last_name %></p>
<p>Fecha: <%= @protocol.created_at %></p>
<p>Tests: <%= @patient.rorschachTests.length %></p>
</br>

<p>
  <strong>Resumen de protocolo:</strong>
	</br>
	<div style="display:inline-block;">
		<%= button_to "Sumario Estructural", { :action => "new" }, :method => :get %>
	</div>
	<div style="display:inline-block;">
		<%= button_to "Hoja de Constelaciones", { :action => "new" }, :method => :get %>
	</div>
	</br>
  <strong>Láminas:</p>
</p>
</br>
<div name="main grid">
	<% @sheets.each do |sheet| %>
		<div name="grid">
			<h2>Lámina <%= sheet.name %></h2>
			<%= link_to protocol_admin_sheet_path(@protocol.id,sheet.id) do
				image_tag(sheet.background, alt: sheet.name+" miniatura", class: "sheet-mini")
				end %>
			<%#= link_to image_tag(sheet.background, border: 1, class: "sheet-mini"), :action => 'search', :controller => 'pages', :class => 'dock-item' %>
			<p>Interpretaciones: 0<%#= @protocol.interpretations.length %> </p>
		</div>
	<% end %>
</div>

<%= link_to 'Back', protocol_admin_index_path %>